#!/bin/bash

function usage {
	echo "USAG: $(basename $0) [-h host] [-u user] [-p port] [-k key] [-f]"
	exit 1
}

USER="$(whoami)"
HOST=''
PORT=22
OWNKEY=''
FORCE=0

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
   	-h)
   	 	HOST="$2"
   	 	shift 2
   	 	;;
   	-u)
   	 	USER="$2"
   	 	shift 2
   	 	;;
   	-p)
   	 	PORT="$2"
   	 	shift 2
   	 	;;
   	-k)
   	 	OWNKEY="$2"
   	 	shift 2
   	 	;;
   	-f)
   	 	FORCE=1	
   	 	shift
   	 	;;
   	 *)
   		usage
   	 	;;
	esac
done

if [ "${HOST}" == "last" -a -f $(dirname $0)/.host ]; then
    HOST=$(cat $(dirname $0)/.host)
else
    echo "${HOST}" > $(dirname $0)/.host
fi

KEY=~/.ssh/${USER}

if [ "${OWNKEY}" != "" ]; then
	OWNKEY=~/.ssh/${OWNKEY}
	if [ ! -f ${OWNKEY} ]; then
		echo "The given key does not exist!"
		exit 1
	fi
fi

if [ ! -f ${KEY} -o ${FORCE} -eq 1 ]; then
	echo "Generating your ssh key..."
	ssh-keygen -q -C "${USER}s key" -N '' -b 4096 -f ${KEY}
else
	echo "Your ssh key exists."
fi

if [ "${OWNKEY}" != "" ]; then
	if [ -f ${OWNKEY} ]; then
		echo "Copy ID to ${USER}@${HOST}:${PORT} using key ${OWNKEY}"
		scp -i ${OWNKEY} -P ${PORT} ${KEY}.pub ${USER}@${HOST}:.ssh
		ssh -i ${OWNKEY} ${USER}@${HOST} -p ${PORT} 'cat .ssh/${USER}.pub >> .ssh/authorized_keys'
	else 
		echo "Key ${OWNKEY} does not exist!"
	fi
elif [ "${HOST}" != "" -a -f ${KEY} ]; then
	echo "Copy ID to ${USER}@${HOST}:${PORT}"
	ssh-copy-id -i $KEY ${USER}@${HOST} -p ${PORT}
fi
